echo ">> Running ~/.zshrc ..."

[ -f ~/.zsh_local/zshrc_local_before.zsh ] && source ~/.zsh_local/zshrc_local_before.zsh

source ~/.zsh/plugins.zsh
source ~/.zsh/settings.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/exports.zsh

[ -f ~/.zsh_local/zshrc_local_after.zsh ] && source ~/.zsh_local/zshrc_local_after.zsh
