echo "setup bashrc"

# allow local customizations in the ~/.bashrc_local_before file
[ -f ~/.bash_local/bashrc_local_before.sh ] && source ~/.bash_local/bashrc_local_before.sh

# settings
source ~/.bash/settings.bash

# aliases/functions (share with zsh)
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh

# allow local customizations in the ~/.bashrc_local_after file
[ -f ~/.bash_local/bashrc_local_after.sh ] && source ~/.bash_local/bashrc_local_after.sh
